[package]
name = "sourcerenderer_game"
version = "0.1.0"
edition = "2024"

[dependencies]
sourcerenderer_core = { path = "../core" }
sourcerenderer_engine = { path = "../engine", default-features = false }
log = "0.4.25"
bevy_app = "0.19"
bevy_math = { version = "0.19", features = ["serialize"] }
bevy_ecs = "0.19"
bevy_transform = "0.19"
bevy_log = "0.19"
bevy_tasks = "0.19"
bevy_utils = "0.19"
bevy_time = "0.19"
bevy_input = "0.19"
