[package]
name = "sourcerenderer_sdl"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
sdl2 = "0.34.5"
sdl2-sys = "0.34.5"
ash = "0.33.1+1.2.186"
bitset-core = "0.1.1"
sourcerenderer_bsp = { path = "../../valve_formats/bsp" }
sourcerenderer_core = { path = "../../core" }
sourcerenderer_vulkan = { path = "../../graphics/vulkan" }
sourcerenderer_engine = { path = "../../engine" }
lazy_static = "1.4.0"
simple_logger = "1.13.0"

[profile.release]
debug = true
