bitflags! {
  pub struct TextureFlags: u32 {
    // Flags from the *.txt config file
    const POINT_SAMPLE = 0x00000001;
    const TRI_LINEAR = 0x00000002;
    const CLAMP_S= 0x00000004;
    const CLAMP_T = 0x00000008;
    const ANISOTROPIC = 0x00000010;
    const HINT_DXT5 = 0x00000020;
    const PWL_CORRECTED = 0x00000040;
    const NORMAL = 0x00000080;
    const NO_MIP = 0x00000100;
    const NO_LOD = 0x00000200;
    const ALL_MIPS = 0x00000400;
    const PROCEDURAL = 0x00000800;

    // These are automatically generated by vtex from the texture data.
    const ONE_BIT_ALPHA = 0x00001000;
    const EIGHT_BIT_ALPHA = 0x00002000;

    // Newer flags from the *.txt config file
    const ENV_MAP = 0x00004000;
    const RENDER_TARGET = 0x00008000;
    const DEPTH_RENDER_TARGET = 0x00010000;
    const NODE_BUG_OVERRIDE = 0x00020000;
    const SINGLE_COPY = 0x00040000;
    const PRE_SRGB = 0x00080000;

    const UNUSED_00100000 = 0x00100000;
    const UNUSED_00200000 = 0x00200000;
    const UNUSED_00400000 = 0x00400000;

    const NO_DEPTH_BUFFER = 0x00800000;

    const UNUSED_01000000 = 0x01000000;

    const CLAMP_U = 0x02000000;
    const VERTEX_TEXTURE = 0x04000000;
    const SS_BUMP = 0x08000000;

    const UNUSED_10000000 = 0x10000000;

    const BORDER = 0x20000000;

    const UNUSED_40000000 = 0x40000000;
    const UNUSED_80000000 = 0x80000000;
  }
}
