[package]
name = "sourcerenderer_vmt"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]
edition = "2018"

[dependencies]
futures-io = "0.3.31"
io_util = { path = "../../io_util" }
