[package]
name = "sourcerenderer_vtx"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]
edition = "2021"

[dependencies]
bitflags = "2.9"
bevy_math = "0.16"
futures-io = "0.3"
io_util = { path = "../../io_util" }
