use std::sync::Arc;

use bevy_app::App;
use sourcerenderer_engine::Engine;

use sourcerenderer_engine::asset::{AssetLoadPriority, AssetManager, AssetType, LevelHandle};

use sourcerenderer_core::platform::PlatformIO;
use sourcerenderer_engine::asset::loaders::load_file_gltf_container;

#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
#[allow(unused)]
pub enum KhronosAsset {
    ABeautifulGame = 0,
    AlphaBlendModeTest = 1,
    AnimatedColorsCube = 2,
    AnimatedCube = 3,
    AnimatedMorphCube = 4,
    AnimatedTriangle = 5,
    AnimationPointerUVs = 6,
    AnisotropyBarnLamp = 7,
    AnisotropyDiscTest = 8,
    AnisotropyRotationTest = 9,
    AnisotropyStrengthTest = 10,
    AntiqueCamera = 11,
    AttenuationTest = 12,
    Avocado = 13,
    BarramundiFish = 14,
    BoomBox = 15,
    BoomBoxWithAxes = 16,
    Box = 17,
    BoxAnimated = 18,
    BoxInterleaved = 19,
    BoxTextured = 20,
    BoxTexturedNonPowerOfTwo = 21,
    BoxVertexColors = 22,
    BoxWithSpaces = 23,
    BrainStem = 24,
    Cameras = 25,
    CarbonFibre = 26,
    CarConcept = 27,
    CesiumMan = 28,
    CesiumMilkTruck = 29,
    ChairDamaskPurplegold = 30,
    ChronographWatch = 31,
    ClearCoatCarPaint = 32,
    ClearCoatTest = 33,
    ClearcoatWicker = 34,
    CommercialRefrigerator = 35,
    CompareAlphaCoverage = 36,
    CompareAmbientOcclusion = 37,
    CompareAnisotropy = 38,
    CompareBaseColor = 39,
    CompareClearcoat = 40,
    CompareDispersion = 41,
    CompareEmissiveStrength = 42,
    CompareIor = 43,
    CompareIridescence = 44,
    CompareMetallic = 45,
    CompareNormal = 46,
    CompareRoughness = 47,
    CompareSheen = 48,
    CompareSpecular = 49,
    CompareTransmission = 50,
    CompareVolume = 51,
    Corset = 52,
    Cube = 53,
    DamagedHelmet = 54,
    DiffuseTransmissionPlant = 55,
    DiffuseTransmissionTeacup = 56,
    DiffuseTransmissionTest = 57,
    DirectionalLight = 58,
    DispersionTest = 59,
    DragonAttenuation = 60,
    DragonDispersion = 61,
    Duck = 62,
    EmissiveStrengthTest = 63,
    EnvironmentTest = 64,
    FlightHelmet = 65,
    Fox = 66,
    GlamVelvetSofa = 67,
    GlassBrokenWindow = 68,
    GlassHurricaneCandleHolder = 69,
    GlassVaseFlowers = 70,
    InterpolationTest = 71,
    IORTestGrid = 72,
    IridescenceAbalone = 73,
    IridescenceDielectricSpheres = 74,
    IridescenceLamp = 75,
    IridescenceMetallicSpheres = 76,
    IridescenceSuzanne = 77,
    IridescentDishWithOlives = 78,
    Lantern = 79,
    LightsPunctualLamp = 80,
    MandarinOrange = 81,
    MaterialsVariantsShoe = 82,
    MeshPrimitiveModes = 83,
    MetalRoughSpheres = 84,
    MetalRoughSpheresNoTextures = 85,
    MorphPrimitivesTest = 86,
    MorphStressTest = 87,
    MosquitoInAmber = 88,
    MultipleScenes = 89,
    MultiUVTest = 90,
    NegativeScaleTest = 91,
    NodePerformanceTest = 92,
    NormalTangentMirrorTest = 93,
    NormalTangentTest = 94,
    OrientationTest = 95,
    PlaysetLightTest = 96,
    PointLightIntensityTest = 97,
    PotOfCoals = 98,
    PotOfCoalsAnimationPointer = 99,
    PrimitiveModeNormalsTest = 100,
    RecursiveSkeletons = 101,
    RiggedFigure = 102,
    RiggedSimple = 103,
    ScatteringSkull = 104,
    SciFiHelmet = 105,
    SheenChair = 106,
    SheenCloth = 107,
    SheenTestGrid = 108,
    SheenWoodLeatherSofa = 109,
    SimpleInstancing = 110,
    SimpleMaterial = 111,
    SimpleMeshes = 112,
    SimpleMorph = 113,
    SimpleSkin = 114,
    SimpleSparseAccessor = 115,
    SimpleTexture = 116,
    SpecGlossVsMetalRough = 117,
    SpecularSilkPouf = 118,
    SpecularTest = 119,
    Sponza = 120,
    StainedGlassLamp = 121,
    SunglassesKhronos = 122,
    Suzanne = 123,
    TextureCoordinateTest = 124,
    TextureEncodingTest = 125,
    TextureLinearInterpolationTest = 126,
    TextureSettingsTest = 127,
    TextureTransformMultiTest = 128,
    TextureTransformTest = 129,
    ToyCar = 130,
    TransmissionOrderTest = 131,
    TransmissionRoughnessTest = 132,
    TransmissionTest = 133,
    TransmissionThinwallTestGrid = 134,
    Triangle = 135,
    TriangleWithoutIndices = 136,
    TwoSidedPlane = 137,
    UnlitTest = 139,
    VertexColorTest = 140,
    VirtualCity = 141,
    WaterBottle = 142,
    XmpMetadataRoundedCube = 143,
}

pub const KHRONOS_ASSET_FOLDERS: &[&str] = &[
    "ABeautifulGame",
    "AlphaBlendModeTest",
    "AnimatedColorsCube",
    "AnimatedCube",
    "AnimatedMorphCube",
    "AnimatedTriangle",
    "AnimationPointerUVs",
    "AnisotropyBarnLamp",
    "AnisotropyDiscTest",
    "AnisotropyRotationTest",
    "AnisotropyStrengthTest",
    "AntiqueCamera",
    "AttenuationTest",
    "Avocado",
    "BarramundiFish",
    "BoomBox",
    "BoomBoxWithAxes",
    "Box",
    "BoxAnimated",
    "BoxInterleaved",
    "BoxTextured",
    "BoxTexturedNonPowerOfTwo",
    "BoxVertexColors",
    "Box With Spaces",
    "BrainStem",
    "Cameras",
    "CarbonFibre",
    "CarConcept",
    "CesiumMan",
    "CesiumMilkTruck",
    "ChairDamaskPurplegold",
    "ChronographWatch",
    "ClearCoatCarPaint",
    "ClearCoatTest",
    "ClearcoatWicker",
    "CommercialRefrigerator",
    "CompareAlphaCoverage",
    "CompareAmbientOcclusion",
    "CompareAnisotropy",
    "CompareBaseColor",
    "CompareClearcoat",
    "CompareDispersion",
    "CompareEmissiveStrength",
    "CompareIor",
    "CompareIridescence",
    "CompareMetallic",
    "CompareNormal",
    "CompareRoughness",
    "CompareSheen",
    "CompareSpecular",
    "CompareTransmission",
    "CompareVolume",
    "Corset",
    "Cube",
    "DamagedHelmet",
    "DiffuseTransmissionPlant",
    "DiffuseTransmissionTeacup",
    "DiffuseTransmissionTest",
    "DirectionalLight",
    "DispersionTest",
    "DragonAttenuation",
    "DragonDispersion",
    "Duck",
    "EmissiveStrengthTest",
    "EnvironmentTest",
    "FlightHelmet",
    "Fox",
    "GlamVelvetSofa",
    "GlassBrokenWindow",
    "GlassHurricaneCandleHolder",
    "GlassVaseFlowers",
    "InterpolationTest",
    "IORTestGrid",
    "IridescenceAbalone",
    "IridescenceDielectricSpheres",
    "IridescenceLamp",
    "IridescenceMetallicSpheres",
    "IridescenceSuzanne",
    "IridescentDishWithOlives",
    "Lantern",
    "LightsPunctualLamp",
    "MandarinOrange",
    "MaterialsVariantsShoe",
    "MeshPrimitiveModes",
    "MetalRoughSpheres",
    "MetalRoughSpheresNoTextures",
    "MorphPrimitivesTest",
    "MorphStressTest",
    "MosquitoInAmber",
    "MultipleScenes",
    "MultiUVTest",
    "NegativeScaleTest",
    "NodePerformanceTest",
    "NormalTangentMirrorTest",
    "NormalTangentTest",
    "OrientationTest",
    "PlaysetLightTest",
    "PointLightIntensityTest",
    "PotOfCoals",
    "PotOfCoalsAnimationPointer",
    "PrimitiveModeNormalsTest",
    "RecursiveSkeletons",
    "RiggedFigure",
    "RiggedSimple",
    "ScatteringSkull",
    "SciFiHelmet",
    "SheenChair",
    "SheenCloth",
    "SheenTestGrid",
    "SheenWoodLeatherSofa",
    "SimpleInstancing",
    "SimpleMaterial",
    "SimpleMeshes",
    "SimpleMorph",
    "SimpleSkin",
    "SimpleSparseAccessor",
    "SimpleTexture",
    "SpecGlossVsMetalRough",
    "SpecularSilkPouf",
    "SpecularTest",
    "Sponza",
    "StainedGlassLamp",
    "SunglassesKhronos",
    "Suzanne",
    "TextureCoordinateTest",
    "TextureEncodingTest",
    "TextureLinearInterpolationTest",
    "TextureSettingsTest",
    "TextureTransformMultiTest",
    "TextureTransformTest",
    "ToyCar",
    "TransmissionOrderTest",
    "TransmissionRoughnessTest",
    "TransmissionTest",
    "TransmissionThinwallTestGrid",
    "Triangle",
    "TriangleWithoutIndices",
    "TwoSidedPlane",
    "UnlitTest",
    "VertexColorTest",
    "VirtualCity",
    "WaterBottle",
    "XmpMetadataRoundedCube",
];

pub fn load_khronos_model<IO: PlatformIO>(app: &App, asset: KhronosAsset) -> LevelHandle {
    let asset_manager: &Arc<AssetManager> = Engine::get_asset_manager(app);

    let name = KHRONOS_ASSET_FOLDERS[asset as u32 as usize];
    let path_glb = format!("assets/KhronosModels/{}/glTF/{}.glb", name, name);
    let path = format!("assets/KhronosModels/{}/glTF/{}.gltf", name, name);

    asset_manager.try_add_container_async(async move {
        load_file_gltf_container::<IO>(&path_glb, true).await
    });

    let scene_path = format!("{}/scene/0", path);
    let (handle, _) = asset_manager.request_asset(&scene_path, AssetType::Level, AssetLoadPriority::Normal);
    handle.into()
}
