#ifndef DESCRIPTOR_SETS_H
#define DESCRIPTOR_SETS_H

#define DESCRIPTOR_SET_VERY_FREQUENT 0
#define DESCRIPTOR_SET_FREQUENT 1
#define DESCRIPTOR_SET_FRAME 2
#define DESCRIPTOR_SET_TEXTURES_BINDLESS 3
#define DESCRIPTOR_SET_BUFFERS_BINDLESS 4

#endif
