#ifndef DESCRIPTOR_SETS_H
#define DESCRIPTOR_SETS_H

#define DESCRIPTOR_SET_PER_DRAW 0
#define DESCRIPTOR_SET_PER_MATERIAL 1
#define DESCRIPTOR_SET_PER_FRAME 2
#define DESCRIPTOR_SET_RARELY 3

#endif
