[package]
name = "sourcerenderer_q3_bsp"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]
edition = "2021"

[dependencies]
bitflags = "2.9"
nalgebra = "0.33"
zip = "2.6"
io_util = { path = "../../io_util" }
