[package]
name = "sourcerenderer_mdl"
version = "0.1.0"
authors = ["Robin Kertels <robin.kertels@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "2.4.2"
bevy_math = "0.15.1"
io_util = { path = "../../io_util" }
