name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install spirv-cross
      run: sudo apt install -y spirv-cross
    - name: Install spirv-cross
      run: sudo apt install -y libsdl3-0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
