name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y glslang-tools

      - name: Setup SDL3
        uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 3-latest
          version-sdl-image: 3-latest

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
